name: Tic-Tac-Toe CI

on: [push, pull_request]  # Triggers

jobs:
  build-and-test:
    runs-on: windows-latest  # Using Windows Server 2022 (analogue Windows 11 for CI)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # clone repository

    - name: Install CMake and MSVC
      shell: powershell
      run: |
        # Installing CMake and MSVC Tools
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install visualstudio2022buildtools -y
        choco install visualstudio2022-workload-vctools -y

    - name: Test message
      shell: bash
      run: |
        echo "Hello from Bash on Windows, WTF???"
        ls -la  # Works

      # Build using bash
    - name: Configure and Build
      shell: bash
      run: |
          mkdir -p build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64
          cmake --build . --config Release
         
        